title: Ashwin Sridharan # your name (or website title) here
logo: "/images/dppiclinkedin.jpg?raw=true" # photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student at Carnegie Mellon
  <br></br>
  Analytics Intern at SAP
  Former Consultant at EY
  <br></br>
  <a href="https://www.linkedin.com/in/ashwinsridharan/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
